name: portfolio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  visibility_detector: ^0.4.0+2
  audioplayers: ^6.5.0
  flame: ^1.30.1
  flame_audio: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dino/
    - assets/images/ground/
    - assets/images/obstacles/
    # - assets/sounds/

  fonts:
    - family: DinoFont
      fonts:
        - asset: assets/fonts/DinoFont.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
